---
kind: pipeline
type: docker
name: test

concurrency:
  limit: 1

steps:
  - name: test
    image: node:lts
    commands:
      - /bin/sh ./setup-firefox.sh
      - yarn install
      - yarn test --filter Account
# trigger:
#   event:
#     - pull_request
#     - rollback
#     - merge
