---
kind: pipeline
type: docker
name: test

concurrency:
  limit: 1

steps:
  - name: test
    image: node:lts-slim
    commands:
      - apt update
      - apt install software-properties-common -y
      - add-apt-repository ppa:mozillateam/ppa
      - apt install firefox -y
      - npm install
      - npm test
# trigger:
#   event:
#     - pull_request
#     - rollback
#     - merge
