---
kind: pipeline
type: docker
name: test

concurrency:
  limit: 1

steps:
  - name: test
    image: node:lts-slim
    commands:
      - apt-get update
      - apt-get install firefox
      - npm install
      - npm test
# trigger:
#   event:
#     - pull_request
#     - rollback
#     - merge
